### ISSUE TITLE
generic "stream override" config option group

### ISSUE THREAD

**Issue by dmarx** [pytti-tools/pytti-core#154]
* link variables together
* link or override variables with external data/streams
* define meta variables?
should be able to accept anything that can be indexed by "t"
maybe separately define streams, and then have an isolated section for setting up links and overrids

**Comment by dmarx** [comment]
something like...
```
data_streams:
- stream_name: x
  stream_type: csv
  stream_source: x_values.csv
- stream_name: y
  stream_type: parametric_eval
  stream_source: "x * t + np.random.normal()"
- stream_name: t_depth
  stream_type: npy
  stream_source: precomputed_depth_maps.npy
stream_overrides:
  adabins.infer: t_depth
```
